--------------------------------------------------------
--  파일이 생성됨 - 금요일-5월-08-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TRIP_RESERVATION
--------------------------------------------------------

  CREATE TABLE "SCOTT"."TRIP_RESERVATION" 
   (	"PACKAGENUM" NUMBER(10,0), 
	"ID" VARCHAR2(20 BYTE), 
	"NO" NUMBER(10,0), 
	"HEADCOUNT" NUMBER(3,0), 
	"STARTDATE" DATE, 
	"VOTECHECK" NUMBER(1,0), 
	"STATUS" NUMBER(2,0), 
	"AIRINFO" VARCHAR2(200 BYTE), 
	"HOTELINFO" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into SCOTT.TRIP_RESERVATION
SET DEFINE OFF;
Insert into SCOTT.TRIP_RESERVATION (PACKAGENUM,ID,NO,HEADCOUNT,STARTDATE,VOTECHECK,STATUS,AIRINFO,HOTELINFO) values (31,'a',17,5,to_date('15/05/05','RR/MM/DD'),0,0,'2015.06.20,2015.06.21','yeshtoel,ibis');
Insert into SCOTT.TRIP_RESERVATION (PACKAGENUM,ID,NO,HEADCOUNT,STARTDATE,VOTECHECK,STATUS,AIRINFO,HOTELINFO) values (42,'m2000jh',22,2,to_date('15/06/13','RR/MM/DD'),0,0,'2015.06.20,2015.06.21','yeshtoel,ibis');
Insert into SCOTT.TRIP_RESERVATION (PACKAGENUM,ID,NO,HEADCOUNT,STARTDATE,VOTECHECK,STATUS,AIRINFO,HOTELINFO) values (34,'m2000jh',26,5,to_date('15/06/13','RR/MM/DD'),0,0,null,null);
Insert into SCOTT.TRIP_RESERVATION (PACKAGENUM,ID,NO,HEADCOUNT,STARTDATE,VOTECHECK,STATUS,AIRINFO,HOTELINFO) values (1,'a',2,3,to_date('15/05/15','RR/MM/DD'),0,3,'2015.06.20,2015.06.21','yeshtoel,ibis');
Insert into SCOTT.TRIP_RESERVATION (PACKAGENUM,ID,NO,HEADCOUNT,STARTDATE,VOTECHECK,STATUS,AIRINFO,HOTELINFO) values (2,'han',15,1,to_date('15/05/06','RR/MM/DD'),0,0,'2015.06.20,2015.06.21','yeshtoel,ibis');
Insert into SCOTT.TRIP_RESERVATION (PACKAGENUM,ID,NO,HEADCOUNT,STARTDATE,VOTECHECK,STATUS,AIRINFO,HOTELINFO) values (2,'ye0823',18,2,to_date('15/05/08','RR/MM/DD'),0,0,'2015.06.20,2015.06.21','yeshtoel,ibis');
Insert into SCOTT.TRIP_RESERVATION (PACKAGENUM,ID,NO,HEADCOUNT,STARTDATE,VOTECHECK,STATUS,AIRINFO,HOTELINFO) values (34,'han',20,10,to_date('15/05/22','RR/MM/DD'),0,0,'2015.06.20,2015.06.21','yeshtoel,ibis');
Insert into SCOTT.TRIP_RESERVATION (PACKAGENUM,ID,NO,HEADCOUNT,STARTDATE,VOTECHECK,STATUS,AIRINFO,HOTELINFO) values (2,'han',12,80,to_date('15/05/11','RR/MM/DD'),0,3,'2015.06.20,2015.06.21','yeshtoel,ibis');
Insert into SCOTT.TRIP_RESERVATION (PACKAGENUM,ID,NO,HEADCOUNT,STARTDATE,VOTECHECK,STATUS,AIRINFO,HOTELINFO) values (34,'han',16,1,to_date('15/05/22','RR/MM/DD'),0,0,'2015.06.20,2015.06.21','yeshtoel,ibis');
Insert into SCOTT.TRIP_RESERVATION (PACKAGENUM,ID,NO,HEADCOUNT,STARTDATE,VOTECHECK,STATUS,AIRINFO,HOTELINFO) values (48,'m2000jh',21,2,to_date('20/04/20','RR/MM/DD'),1,2,'2015.06.20,2015.06.21','yeshtoel,ibis');
Insert into SCOTT.TRIP_RESERVATION (PACKAGENUM,ID,NO,HEADCOUNT,STARTDATE,VOTECHECK,STATUS,AIRINFO,HOTELINFO) values (50,'m2000jh',23,3,to_date('15/06/21','RR/MM/DD'),0,1,'2015.06.20,2015.06.21','yeshtoel,ibis');
Insert into SCOTT.TRIP_RESERVATION (PACKAGENUM,ID,NO,HEADCOUNT,STARTDATE,VOTECHECK,STATUS,AIRINFO,HOTELINFO) values (51,'m2000jh',24,3,to_date('14/07/16','RR/MM/DD'),1,2,'2015.06.20,2015.06.21','yeshtoel,ibis');
Insert into SCOTT.TRIP_RESERVATION (PACKAGENUM,ID,NO,HEADCOUNT,STARTDATE,VOTECHECK,STATUS,AIRINFO,HOTELINFO) values (34,'m2000jh',25,2,to_date('15/06/13','RR/MM/DD'),0,0,null,null);
--------------------------------------------------------
--  DDL for Index RESERVATION_NO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."RESERVATION_NO_PK" ON "SCOTT"."TRIP_RESERVATION" ("NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table TRIP_RESERVATION
--------------------------------------------------------

  ALTER TABLE "SCOTT"."TRIP_RESERVATION" ADD CONSTRAINT "RESERVATION_NO_PK" PRIMARY KEY ("NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "SCOTT"."TRIP_RESERVATION" MODIFY ("HEADCOUNT" NOT NULL ENABLE);
 
  ALTER TABLE "SCOTT"."TRIP_RESERVATION" MODIFY ("STARTDATE" NOT NULL ENABLE);
 
  ALTER TABLE "SCOTT"."TRIP_RESERVATION" MODIFY ("STATUS" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table TRIP_RESERVATION
--------------------------------------------------------

  ALTER TABLE "SCOTT"."TRIP_RESERVATION" ADD CONSTRAINT "RESERVATION_ID_FK" FOREIGN KEY ("ID")
	  REFERENCES "SCOTT"."TRIP_USER" ("ID") ENABLE;
 
  ALTER TABLE "SCOTT"."TRIP_RESERVATION" ADD CONSTRAINT "RESERVATION_PN_FK" FOREIGN KEY ("PACKAGENUM")
	  REFERENCES "SCOTT"."TRIP_PACKAGE" ("PACKAGENUM") ENABLE;
